"""update database schema

Revision ID: ada7c53bce94
Revises: 59ed8f84cc96
Create Date: 2026-09-10 03:30:36.715515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ada7c53bce94'
down_revision: Union[str, Sequence[str], None] = '59ed8f84cc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_matches_resume_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_resume_score'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_user_created'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_job_search_results_conversation_id'), table_name='job_search_results')
    op.drop_index(op.f('ix_job_search_results_user_created'), table_name='job_search_results')
    op.drop_index(op.f('ix_job_search_results_user_id'), table_name='job_search_results')
    op.drop_table('job_search_results')
    op.add_column('messages', sa.Column('tool_name', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('tool_call_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('tool_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('resumes', 'filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.alter_column('resumes', 'filename',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'tool_data')
    op.drop_column('messages', 'tool_call_id')
    op.drop_column('messages', 'tool_name')
    op.create_table('job_search_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('search_query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('job_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('job_search_results_conversation_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_search_results_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_search_results_pkey'))
    )
    op.create_index(op.f('ix_job_search_results_user_id'), 'job_search_results', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_search_results_user_created'), 'job_search_results', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_search_results_conversation_id'), 'job_search_results', ['conversation_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('job_matches_resume_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_matches_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_matches_pkey'))
    )
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_matches_user_created'), 'job_matches', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_matches_resume_score'), 'job_matches', ['resume_id', 'match_score'], unique=False)
    op.create_index(op.f('ix_job_matches_resume_id'), 'job_matches', ['resume_id'], unique=False)
    # ### end Alembic commands ###
